Feat join group from list
polypoly-team/android-app pull request #51
Opened 2023-03-29 10:54 UTC by Kaz-ookid

Implemented a button in **JoinGroupActivity** that opens a dialog filled with the list of Public and not full groups in the DB. This list if refreshed every 5 seconds. 

It is safe to try and join a group that shows as not full in the client side but is in the DB side, it will just prompt that the group is full and will disappear within the next refresh.

The list of groups is showed as bars that containt the name of the group and the number of players in it, as well as the maximum number of players. It show as so: `Group name         'avatar icon' 3/5`
These bars are clickable, and once clicked un-rolls the whole details of the lobby: name and profile pictures of the players in the lobby, game mode, round duration and a `Join` button that lets the user join the given group.

Tests are not yet implemented and that is the reason this is a **draft pull request**

2023-03-30 23:44 UTC, Kaz-ookid commented
Replaced mock implementation with the use of Fake DB that uses the same interface as the real DB. Will work well once the real DB queries are up. Tests are not yet finished but should work well anyway.

2023-03-31 15:52 UTC, Jharaxus requested changes
A couple of refactoring is still needed, but great overall job!

2023-03-31 15:52 UTC, Jharaxus commented on app/src/main/java/com/github/polypoly/app/network/FakeRemoteStorage.kt
> +        gameLobbyPrivate.addUser(testUser4)
This could be refactored with a function `addUsersToGroups` to make one-line assignments instead per `GameLobby` instead.

2023-03-31 20:14 UTC, Jharaxus approved these changes
Great, this looks to work fine !

2023-03-31 22:45 UTC, AlSchlo commented on app/src/androidTest/java/com/github/polypoly/app/JoinGameLobbyActivityTest.kt
> +    fun launchActivity_componentsDisplayed() {
Weird mix of camelCase and snake_case

2023-03-31 22:51 UTC, AlSchlo commented on app/src/main/java/com/github/polypoly/app/network/FakeRemoteStorage.kt
>  class FakeRemoteStorage : IRemoteStorage {
Why has FakeRemoteStorage become a storage for game lobbies, users, etc.? This looks like bad abstraction.

2023-03-31 22:56 UTC, AlSchlo commented on app/src/main/java/com/github/polypoly/app/network/IRemoteStorage.kt
>  interface IRemoteStorage {
Your remote storage is poorly abstracted. It should not be directly responsible for managing GameLobbies

2023-04-01 16:09 UTC, merged