Add OpenStreetMap map
polypoly-team/android-app pull request #8
Opened 2023-03-03 20:14 UTC by jadtl

This adds an OpenStreetMap map using osmdroid, the map activity displays the EPFL campus at start. Internet permission had to be added to `AndroidManifest.xml` for the map to work.

2023-03-08 11:52 UTC, jadtl commented
I updated the activity to use Compose :)

2023-03-09 17:37 UTC, Jharaxus requested changes
A little detail to change but apart from that it looks good to me!

2023-03-09 17:37 UTC, Jharaxus commented on app/src/main/java/com/github/polypoly/app/MapActivity.kt
> +import androidx.appcompat.app.AppCompatActivity
According to AndroidStudio this last import is useless and can be removed

2023-03-10 14:20 UTC, Jharaxus approved these changes
Nice this fix the previous issue, everything looks fine now.

2023-03-10 14:22 UTC, merged