Bootcamp/kotlin
polypoly-team/android-app pull request #9
Opened 2023-03-03 20:17 UTC by vrooomer

This branch corresponds to our migration from Kotlin and the basic XML UI gestion to Kotlin & Jetpack compose.
For this purpose, I needed to recreate the project from scratch.

In this version, we have the classic bootcamp working, i.e. a place where to put you name (can't be empty and max. 15 characters) and a button that shows a screen with a personalized greeting message.

Both two activities were tested (with Jetpack compose & Espresso) in the same fashion of the classic bootcamp.

If we are 100% sure to migrate to Compose, this request should be carefully reviewed and understood as this will the base of our project.

If you have any comments, feel free to ask me!

~ v:)

2023-03-07 07:54 UTC, jadtl requested changes
Thanks for the PR :)
Nitpick: the package name for the project should be something like `com.github.polypoly.app` instead of `com.github.vroomer.polypoly`

2023-03-07 07:54 UTC, jadtl commented on settings.gradle
> -ext.isCiServer = System.getenv().containsKey("CIRRUS_CI")
Thanks for the PR :)
These lines should be kept for the CI to run correctly, and the PR is also missing the `.cirrus.yml` and `.codeclimate.yml` files.

2023-03-07 21:22 UTC, vrooomer commented
Thanks for the comments, I fixed everything :)

- v:)

2023-03-08 07:32 UTC, jadtl approved these changes
LGTM, thanks :)

2023-03-08 07:34 UTC, merged